import {cookies} from 'next/headers';import type {CastSession,Reservation,ReservationInput,Staff} from '@/types/consultation';import {validateReservationInput,sanitizeText} from '@/validation/consultation';
const g=globalThis as typeof globalThis & {__reservations?:Reservation[];__idem?:Map<string,string>};g.__reservations??=[];g.__idem??=new Map();
export const sessionCookie='support_session';export const mockSession:CastSession={castId:'cast_mock_001',castName:'山田 はるか',stores:[{id:'store_001',name:'ミント新宿店'},{id:'store_002',name:'ミント池袋店'}]};
export async function getSession(){return (await cookies()).get(sessionCookie)?.value==='mock-session'?mockSession:null}
export async function requireSession(){const s=await getSession();if(!s)throw Object.assign(new Error('Unauthorized'),{status:401});return s}
export const staff:Staff[]=[{id:'staff_omakase',name:'おまかせ',methods:['in_person','phone','line','online']},{id:'staff_001',name:'佐藤',methods:['in_person','line']},{id:'staff_002',name:'鈴木',methods:['phone','online']}];
export function availability(date:string){const base=new Date(`${date}T10:00:00+09:00`);return Array.from({length:10},(_,i)=>{const s=new Date(base.getTime()+i*30*60000);const e=new Date(s.getTime()+15*60000);const taken=g.__reservations!.some(r=>r.scheduledStartAt===s.toISOString()&&!r.status.startsWith('cancelled'));return {startAt:s.toISOString(),endAt:e.toISOString(),available:!taken&&s.getTime()>Date.now()+60*60000,methods:['in_person','phone','line','online'] as const,staffIds:staff.map(x=>x.id)}})}
export async function listReservations(){const s=await requireSession();return g.__reservations!.filter(r=>r.castId===s.castId)}
export async function getReservation(id:string){const s=await requireSession();return g.__reservations!.find(r=>r.id===id&&r.castId===s.castId)}
export async function createReservation(input:ReservationInput){const s=await requireSession();const prior=g.__idem!.get(input.idempotencyKey);if(prior)return getReservation(prior);const errors=validateReservationInput(input);if(errors.length)throw Object.assign(new Error(errors.join('\n')),{status:422});if(g.__reservations!.some(r=>r.castId===s.castId&&r.scheduledStartAt===input.scheduledStartAt&&!r.status.startsWith('cancelled')))throw Object.assign(new Error('同じ時間帯に予約済みの相談タイムがあります。'),{status:409});const now=new Date().toISOString();const r:Reservation={id:crypto.randomUUID(),reservationNumber:`ST-${Date.now().toString().slice(-8)}`,castId:s.castId,storeId:input.storeId,requestedStaffId:input.requestedStaffId,assignedStaffId:input.requestedStaffId==='staff_omakase'?null:input.requestedStaffId,scheduledStartAt:input.scheduledStartAt,scheduledEndAt:input.scheduledEndAt,consultationMethod:input.consultationMethod,status:input.requestedStaffId==='staff_omakase'?'pending_assignment':'reserved',priority:input.specialRequests.includes('急ぎで相談したい')?'urgent':'normal',categories:input.categories,advanceNote:sanitizeText(input.advanceNote||''),specialRequests:input.specialRequests,bookingSource:'supportブラウザLP',createdAt:now,updatedAt:now,adminSyncStatus:process.env.NEXT_PUBLIC_API_MODE==='production'?'pending':'mock'};g.__reservations!.push(r);g.__idem!.set(input.idempotencyKey,r.id);return r}
export async function updateReservation(id:string,input:Partial<ReservationInput>){const r=await getReservation(id);if(!r)return null;Object.assign(r,{...input,advanceNote:input.advanceNote?sanitizeText(input.advanceNote):r.advanceNote,updatedAt:new Date().toISOString()});return r}
export async function cancelReservation(id:string,reason:string){const r=await getReservation(id);if(!r)return null;r.status='cancelled_by_cast';r.cancelReason=sanitizeText(reason);r.cancelledAt=new Date().toISOString();r.updatedAt=r.cancelledAt;return r}
