import type {AvailabilitySlot,CategoryCode,Method,Reservation,Status} from './types';
const KEY='support-consultation-reservations-v1';
export const useMock=(import.meta.env.VITE_CONSULTATION_API_MODE??'mock')==='mock';
const cast={id:'cast_001',name:'佐藤 みなみ',storeId:'store_001',storeName:'ミント新宿'};
const staff=[{id:'staff_1',name:'田中'},{id:'staff_2',name:'鈴木（女性）'}];
const load=():Reservation[]=>JSON.parse(localStorage.getItem(KEY)??'[]');
const save=(rows:Reservation[])=>localStorage.setItem(KEY,JSON.stringify(rows));
const apiBase=import.meta.env.VITE_CONSULTATION_API_BASE_URL??'';
async function real<T>(path:string,init?:RequestInit){const r=await fetch(`${apiBase}${path}`,{headers:{'Content-Type':'application/json'},...init}); if(!r.ok) throw new Error(await r.text()); return r.json() as Promise<T>}
export const currentCast=()=>cast;
export async function availability(date?:string):Promise<AvailabilitySlot[]>{if(!useMock)return real('/api/cast/consultation/availability'+(date?`?date=${date}`:'')); const d=date??new Date(Date.now()+86400000).toISOString().slice(0,10); const booked=new Set(load().filter(r=>!r.status.startsWith('cancelled')).map(r=>r.scheduledStartAt)); return ['11:00','11:15','11:30','14:00','16:30','18:00'].map((time,i)=>{const startAt=`${d}T${time}:00`; const full=booked.has(startAt)||i===2; return {date:d,time,startAt,endAt:`${d}T${time.slice(0,2)}:${String(Number(time.slice(3))+15).padStart(2,'0')}:00`,methods:i%2?[ 'online','line'] as Method[]:['in_person','phone','line'] as Method[],staff:i<4?staff:[],full,available:!full,reason:full?'満枠':undefined}})}
export async function listReservations(scope:'cast'|'admin'='cast'){if(!useMock)return real<Reservation[]>(scope==='cast'?'/api/cast/consultation/reservations':'/api/admin/consultation/reservations'); return load().sort((a,b)=>a.scheduledStartAt.localeCompare(b.scheduledStartAt))}
export async function getReservation(id:string,scope:'cast'|'admin'='cast'){if(!useMock)return real<Reservation>(`${scope==='cast'?'/api/cast/consultation/reservations':'/api/admin/consultation/reservations'}/${id}`); const r=load().find(x=>x.id===id); if(!r) throw new Error('not found'); return r}
export async function createReservation(input:{slot:AvailabilitySlot;method:Method;staffId?:string;categories:CategoryCode[];advanceNote?:string;specialRequests:string[]}):Promise<Reservation>{if(!useMock)return real('/api/cast/consultation/reservations',{method:'POST',body:JSON.stringify(input)}); if(!input.categories.length) throw new Error('相談カテゴリを選択してください'); if((input.advanceNote??'').length>1000) throw new Error('事前相談内容は1,000文字以内で入力してください'); if(load().some(r=>r.scheduledStartAt===input.slot.startAt&&!r.status.startsWith('cancelled'))) throw new Error('選択した時間は直前に予約が入りました。別の時間を選択してください。'); const s=staff.find(x=>x.id===input.staffId); const now=new Date().toISOString(); const r:Reservation={id:crypto.randomUUID(),reservationNumber:`CT-${Date.now().toString().slice(-8)}`,castId:cast.id,castName:cast.name,storeId:cast.storeId,storeName:cast.storeName,assignedStaffId:s?.id,assignedStaffName:s?.name,scheduledStartAt:input.slot.startAt,scheduledEndAt:input.slot.endAt,method:input.method,status:s?'reserved':'pending_assignment',priority:input.specialRequests.includes('急ぎで相談したい')?'urgent':'normal',categories:input.categories,advanceNote:input.advanceNote?.replace(/<[^>]*>/g,''),specialRequests:input.specialRequests,bookingSource:'キャストLP予約',createdAt:now,updatedAt:now}; save([...load(),r]); return r}
export async function updateReservation(id:string,input:Partial<Reservation>){if(!useMock)return real(`/api/cast/consultation/reservations/${id}`,{method:'PATCH',body:JSON.stringify(input)}); const rows=load(); const i=rows.findIndex(r=>r.id===id); rows[i]={...rows[i],...input,updatedAt:new Date().toISOString()}; save(rows); return rows[i]}
export async function cancelReservation(id:string,reason?:string){return updateReservation(id,{status:'cancelled_by_cast' as Status,cancelReason:reason})}
export async function adminComplete(id:string){return updateReservation(id,{status:'completed',completedRecordId:`record_${Date.now()}`})}
